# fly.toml app configuration file generated for backend-gentle-harborbird-7576 on 2026-04-28T12:12:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-gentle-harborbird-7576'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  size = 'shared-cpu-1x'
